eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8765/eureka/
druid: 
  datasource: 
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://172.25.150.153:1433;databaseName=Leasehold
    username: tslc_test
    password: tslc_test123.
    validationQueryTimeout: 10

#mybatis config
mybatis:
  typeAliasesPackage: com.tslc.**.model
